"""Protect plugin notification provider destinations.

Revision ID: a1a6b04b3606
Revises: c4771032f3c4
Create Date: 2026-10-09 14:21:21.658393

Autogenerated with Compose/Alembic, then reviewed. Unrelated historical
 game-note table drops are excluded. Existing providers retain their legacy
 transport; destinations and credentials are not automatically moved.
"""

import sqlalchemy as sa
from alembic import op

revision: str = "a1a6b04b3606"
down_revision: str | None = "c4771032f3c4"
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # Also adopt metadata-created databases and support the normal safe rerun.
    columns = sa.inspect(op.get_bind()).get_columns("plugin_notification_provider_registrations")
    if any(column["name"] == "transport" for column in columns):
        return
    op.add_column(
        "plugin_notification_provider_registrations",
        sa.Column("transport", sa.String(length=32), server_default="legacy", nullable=False),
    )


def downgrade() -> None:
    # A protected registration cannot safely become a legacy shared-secret sender.
    count = op.get_bind().scalar(
        sa.text(
            "SELECT count(*) FROM plugin_notification_provider_registrations WHERE transport <> 'legacy'"
        )
    )
    if count:
        raise RuntimeError("Remove protected provider registrations before downgrading")
    op.drop_column("plugin_notification_provider_registrations", "transport")
